# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcppeigen_hello_world <- function() {
    .Call('RHODLR_rcppeigen_hello_world', PACKAGE = 'RHODLR')
}

rcppeigen_outerproduct <- function(x) {
    .Call('RHODLR_rcppeigen_outerproduct', PACKAGE = 'RHODLR', x)
}

rcppeigen_innerproduct <- function(x) {
    .Call('RHODLR_rcppeigen_innerproduct', PACKAGE = 'RHODLR', x)
}

rcppeigen_bothproducts <- function(x) {
    .Call('RHODLR_rcppeigen_bothproducts', PACKAGE = 'RHODLR', x)
}

